name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.2", "8.3"]
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip, rdkafka
          tools: composer
        env:
          fail-fast: true

      - run: sudo apt install php-pear

      - run: sudo apt-get install -y librdkafka-dev
      
      - run: sudo echo "extension=rdkafka.so" | sudo tee -a /etc/php/${{matrix.php}}/cli/php.ini
      
      - run: sudo cat /etc/php/${{matrix.php}}/cli/php.ini
      
      - run: sudo cat /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
      
      - run: sudo pecl install rdkafka
      
      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
  

      - run: bash docker/start.sh

      - run: vendor/bin/phpunit --testsuite Tests

