name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.2", "8.3"]
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip
          tools: composer
        env:
          fail-fast: true

      - run: sudo apt install php-pear

      - run: sudo apt-get install -y librdkafka-dev

      - run: sudo pecl install rdkafka

      - run: sudo ls -la /usr/local/etc/php/conf.d/

      - run: sudo echo "extension=rdkafka.so" > /usr/local/etc/php/conf.d/rdkafka.ini

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          php_extensions: rdkafka 
      

      - run: bash docker/start.sh

      - run: vendor/bin/phpunit --testsuite Tests

